// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

// Injectors from wire.go:

func InitializeApplication() (App, func(), error) {
	app := ProvideApp()
	return app, func() {
	}, nil
}
